### ISSUE TITLE
关于训练设备

### ISSUE THREAD

**Issue by brueyq** [lqzhao/SAFNet#1]
您好，我查看了您的训练日志。您是用了4张1080ti来训练和测试这个网络的吗

**Comment by lqzhao** [comment]
您好，是的，我的实验环境如下：
PyTorch version: 1.2.0
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.18.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
